<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Products\Module'                        => __DIR__ . '/Module.php',
    'Products\Controller\ProductsController' => __DIR__ . '/src/Products/Controller/ProductsController.php',
    'ProductsTest\Framework\TestCase'        => __DIR__ . '/tests/Products/Framework/TestCase.php',
    'ProductsTest\SampleTest'                => __DIR__ . '/tests/Products/SampleTest.php',
);