<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ProductsRest\Module'                        => __DIR__ . '/Module.php',
    'ProductsRest\Controller\ProductsController' => __DIR__ . '/src/ProductsRest/Controller/ProductsController.php',
    'ProductsRestTest\Framework\TestCase'        => __DIR__ . '/tests/ProductsRest/Framework/TestCase.php',
    'ProductsRestTest\SampleTest'                => __DIR__ . '/tests/ProductsRest/SampleTest.php',
);